server:
  port: 80
debug: true
spring:
  application:
    name: cloud-consumer-order
eureka:
  instance:
    hostname: localhost #eureka服务注册地址
  client:
    #是否从eureka Server 抓取已有的注册信息，默认true，单节点无所谓，集群必须为true才能配合ribbon使用负载均衡
    fetch-registry: true
    #表示是否将自己加入eureka service true代表加入
    register-with-eureka: true
    service-url:
      #      #设置 eureka server 交互的地址查询服务和注册服务需要依赖的地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka