server:
  port: 8001

spring:
  application:
    name: nacos-payment-consumer
  cloud:
    nacos:
      discovery:
        #        配置 nacos地址
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        exclude: '*'