server:
  port: 8002
spring:
  application:
    name: cloud-payment-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yao?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cpown.springcloud.entities
eureka:
  instance:
    hostname: localhost #eureka服务注册地址
    instance-id: payment8002 #主机名称  配置过后会在eureka监控页面看到
    #配置为 true 可以在网页服务名称下面看到ip地址
    prefer-ip-address: true
  client:
    #是否从eureka Server 抓取已有的注册信息，默认true，单节点无所谓，集群必须为true才能配合ribbon使用负载均衡
    fetch-registry: true
    #表示是否将自己加入eureka service true代表加入
    register-with-eureka: true
    service-url:
      #      #设置 eureka server 交互的地址查询服务和注册服务需要依赖的地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka